### ISSUE TITLE
Page improvements

### ISSUE THREAD

**Issue by steroyle** [itsdhruvarora/Music-Player-Coding-Ninjas#3]
**Home page (index.html)**
- Logo stretches out of proportion on screens wider than 1700px
- Wishlist icons aren't accessible via tabbing

**Inner Page (index2.html)**
- Profile image url is broken

**Comment by steroyle** [comment]
PR created: https://github.com/itsdhruvarora/Music-Player-Coding-Ninjas/pull/4

**Comment by tejasjaiswal07** [comment]
Hey @steroyle, can you please assign me to this issue, I would love to contribute 
thank you!
